version: '3.8'

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - jenkins-home:/var/jenkins_home
    ports:
      - "8080:8080"

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    ports:
      - 8081:8081

volumes:
  jenkins-home:
    external: true
  nexus-data:
    external: true